### ISSUE TITLE
生日快乐！

### ISSUE THREAD

**Issue by xitaoque** [yogu2017/one-mui#1]
请回复你的快递地址，我送你一本第二版吧。
这书现在还没印刷完，我下周三左右寄给你，你下周末应当能收到。
Happy birthday!

**Comment by yogu2017** [comment]
抱歉。才看到回复，最近小宝刚出世一直忙着小宝的事情，没来得及回复
江苏省南京市秦淮区标营3号405 王路路 18551625251

**Comment by yogu2017** [comment]
@xitaoque 抱歉，最近因家中小宝出生，没有及时回复，抱歉，我的地址：江苏省南京市秦淮区标营3号405.王路璐 18551625251，谢谢你的生日祝福！

**Comment by xitaoque** [comment]
这个地址正确吗？百度了下，很多地址都是秦淮区后标营

**Comment by yogu2017** [comment]
嗯，地址对的，是在军管区……

发自我的 iPhone

**Comment by xitaoque** [comment]
圆通速递，500454273238
